name: Test Action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: 'acemod/ace3'
          path: 'ace3'
      - name: Test Setup HEMTT
        uses: ./
        with:
          version: 'latest'
      - name: Run HEMTT
        run: hemtt dev
        working-directory: ace3
